### ISSUE TITLE
List of Linux packages installing the font

### ISSUE THREAD

**Issue by jonasstein** [hikikomori82/osifont#3]
could you provide a list in the readme which package in a Linux distribution installs the osifont, if there are any packages already? Thank you.

**Comment by hikikomori82** [comment]
Hi

I'm not aware that any linux distribution uses osifont, i think there is
some unofficial package for archlinux somewhere but i don't know any
details.

2017-01-01 22:34 GMT+01:00 Jonas Stein <notifications@github.com>:

**Comment by kkremitzki** [comment]
Since FreeCAD 0.17's TechDraw technical drawing workbench uses this font, I am packaging it for Debian as `fonts-osifont`. This means that once it makes its way into testing, it will also be available on downstream distributions like Ubuntu and Linux Mint, as well. Thanks for your work on this font and hopefully this helps more people get use out of it!

**Comment by alexmyczko** [comment]
it's not listed yet anywhere by repology.org (search for fonts-osifont and/or fonts:osifont)
The most difficult part is writing the debian/copyright: GPL-3+FE or GPL-2+FE or LGPL-3+FE

Why not just make it OFL?
